- id: sbt-fatal-warnings
  name: Scala fatal warnings
  stages: [pre-commit, pre-push]
  language: python
  entry: sbt-fatal-warnings
  pass_filenames: false
  minimum_pre_commit_version: "0.19.0"
- id: sbt-unused-imports
  name: Scala unused imports (+ fatal warnings)
  stages: [pre-commit, pre-push]
  language: python
  entry: sbt-fatal-warnings --add_arg='-Ywarn-unused-import'
  pass_filenames: false
  minimum_pre_commit_version: "0.19.0"
- id: sbt-scalafmt
  alias: scalafmt
  name: scalafmt formatting check
  stages: [pre-commit, pre-push]
  language: python
  entry: scalafmt
  pass_filenames: false
  minimum_pre_commit_version: "0.19.0"
- id: sbt-wartremover
  name: Scala WartRemover plugin check
  stages: [pre-commit, pre-push]
  language: python
  entry: sbt-wartremover
  pass_filenames: false
  minimum_pre_commit_version: "0.19.0"
- id: sbt-scalafmt-apply
  alias: scalafmt-apply
  name: scalafmt formatting fix
  stages: [pre-commit, pre-push]
  language: python
  entry: scalafmt-apply
  pass_filenames: false
  minimum_pre_commit_version: "0.19.0"
